### ISSUE TITLE
recent pypilot fails to start (in BBN OS)

### ISSUE THREAD

**Issue by mgrouch** [pypilot/pypilot#102]
Aug 29 01:17:21 lysmarine systemd[1]: Started pypilot.
Aug 29 01:17:22 lysmarine pypilot[17332]: ERROR loading wind.py cannot import name 'HeadingOffset' from 'pypilot.autopilot' (/usr/local/lib/python3.7/dist-packages/pypilot-0.30-py3.7-linux-armv7l.egg/pypilot/autopilot.py)   cannot import name 'HeadingOffset' from 'pypilot.autopilot' (/usr/local/lib/python3.7/dist-packages/pypilot-0.30-py3.7-linux-armv7l.egg/pypilot/autopilot.py)
Aug 29 01:17:22 lysmarine pypilot[17332]: Settings file not found. Using defaults and creating settings file
Aug 29 01:17:22 lysmarine pypilot[17332]: loading servo calibration /home/pypilot/.pypilot/servocalibration
Aug 29 01:17:22 lysmarine pypilot[17332]: WARNING: using default servo calibration!!
Aug 29 01:17:22 lysmarine pypilot[17332]: Available Pilots: ['absolute', 'basic', 'autotune']
Aug 29 01:17:22 lysmarine pypilot[17332]: warning: failed to open special file /dev/watchdog0 for writing
Aug 29 01:17:22 lysmarine pypilot[17332]:          cannot stroke the watchdog
Aug 29 01:17:22 lysmarine pypilot[17332]: Traceback (most recent call last):
Aug 29 01:17:22 lysmarine pypilot[17332]:   File "/usr/local/bin/pypilot", line 11, in <module>
Aug 29 01:17:22 lysmarine pypilot[17332]:     load_entry_point('pypilot==0.30', 'console_scripts', 'pypilot')()
Aug 29 01:17:22 lysmarine pypilot[17332]:   File "/usr/local/lib/python3.7/dist-packages/pypilot-0.30-py3.7-linux-armv7l.egg/pypilot/autopilot.py", line 457, in main
Aug 29 01:17:22 lysmarine pypilot[17332]:     ap.iteration()
Aug 29 01:17:22 lysmarine pypilot[17332]:   File "/usr/local/lib/python3.7/dist-packages/pypilot-0.30-py3.7-linux-armv7l.egg/pypilot/autopilot.py", line 391, in iteration
Aug 29 01:17:22 lysmarine pypilot[17332]:     heading_command_diff = resolv(self.heading_command.value - self.last_heading_command)
Aug 29 01:17:22 lysmarine pypilot[17332]: AttributeError: 'Autopilot' object has no attribute 'last_heading_command'
Aug 29 01:17:22 lysmarine pypilot[17332]: Error in atexit._run_exitfuncs:
Aug 29 01:17:22 lysmarine pypilot[17332]: Traceback (most recent call last):
Aug 29 01:17:22 lysmarine pypilot[17332]:   File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
Aug 29 01:17:22 lysmarine pypilot[17332]:     pid, sts = os.waitpid(self.pid, flag)
Aug 29 01:17:22 lysmarine pypilot[17332]:   File "/usr/local/lib/python3.7/dist-packages/pypilot-0.30-py3.7-linux-armv7l.egg/pypilot/autopilot.py", line 194, in cleanup
Aug 29 01:17:22 lysmarine pypilot[17332]:     raise KeyboardInterrupt # to get backtrace on all processes
Aug 29 01:17:22 lysmarine pypilot[17332]: KeyboardInterrupt
Aug 29 01:17:22 lysmarine pypilot[17332]: closing autopilot

**Comment by seandepagnier** [comment]
I had made some mistakes merging, thanks for reporting this.
