### ISSUE TITLE
Syntaxerror in dependencies.py

### ISSUE THREAD

**Issue by krez** [pypilot/pypilot#106]
Hi. I got an error when trying to install pypilot.

sudo python3 setup.py install
/usr/bin/apt
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    import dependencies
  File "/home/pi/pypilot/dependencies.py", line 88
    os.system('git clone https://github.com/wiringPi/wiringPi'):
                                                               
SyntaxError: invalid syntax

It works if I remove the ":"

**Comment by seandepagnier** [comment]
Thanks!  I made a typo.
