### ISSUE TITLE
Does pypilot provide rate of turn?

### ISSUE THREAD

**Issue by mgrouch** [pypilot/pypilot#116]

**Comment by seandepagnier** [comment]
no but it could

**Comment by peterdrost** [comment]
I would like to have RoT as an output from pyPilot.

**Comment by seandepagnier** [comment]
by nmea? signalk?

**Comment by peterdrost** [comment]
I would like it to be by nmea if possible, as it will be  available
directly om my boats network.
Regards
Peter


ons. 22. dec. 2021 21.43 skrev seandepagnier ***@***.***>:

**Comment by seandepagnier** [comment]
added nmea as well as signalk rate of turn outputs
