### ISSUE TITLE
Idea: Truncate BBN OS to run just pypilot on pi zero 2

### ISSUE THREAD

**Issue by mgrouch** [pypilot/pypilot#153]
Idea: Truncate BBN OS to run just pypilot on pi zero 2.

I can create a separate image for BBN OS by truncating it to run just pypilot, and pi zero 2 hardware.
So it's going to be headless. But based on Bullseye and 64 bit. (can be 32 bit with more work)

I've played with it and made experimental images for pi zero 2 before based on buster.

Should I attempt? I do not have pypilot hardware to test. But given that some people use pypilot on BBN regular version
it shouldn't be difficult to cut it down. I'd need to some help testing it though.

Whole CI is pretty efficient. Push triggers a build. Which nowadays takes under one hour in CircleCi for whole BBN OS (2.8 Gb image .xz and half of that time is just compressing) with upload of .xz image to couldsmith.

For just pypilot it might take under 30 mins. I'd expect image size in 800Gb or so. I can create a branch for it in github where you can commit directly.

Thanks

**Comment by seandepagnier** [comment]
what is the purpose?   There is already tinypilot for the pi zero 2 using tinycore 13.

If you can get BBN to work on other sbc, and especially if you can boot into a ramdisk environment (can remove sd card after boot without issues) that would be really interesting.

**Comment by mgrouch** [comment]
Which SBC? I think I could do Armbian for some other SBC
For pypilot only or for whole thing?

Thanks
