### ISSUE TITLE
pypilot is crashing when servo.rudder value is transmitted to nmea

### ISSUE THREAD

**Issue by smoothfroggy** [pypilot/pypilot#16]
Pypilot is crashing when servo rudder data (servo.rudder) is present in signalK stream from arduino motor driver.

Rough observations:
  - nmea class from nmea.py does not appear to have 'rudder' attribute expected by lines 370 & 371:
>     self.rudder.source.update('servo')
>     self.rudder.angle.update(value)
  - val does not seem to appear as expected by the code in line 372:
>     self.handle_messages({'rudder': val}, 'servo')

*********************************
Log and traceback (launching pypilot through terminal):
loading servo calibration /home/pi/.pypilot/servocalibration
WARNING: using default servo calibration!!
warning: failed to open special file /dev/watchdog0 for writing
         cannot stroke the watchdog
connected to gpsd
Settings file not found. Using defaults and creating settings file
Failed to open settings file for saveUsing settings file RTIMULib.ini
Detected MPU9250/MPU9255 at standard address
Failed to open settings file for saveUsing fusion algorithm Kalman STATE4
IMU Name: MPU-925x
min/max compass calibration not in use
Using ellipsoid compass calibration
Using accel calibration
nmea poll times 0.144361019135 1.71661376953e-05 1.38282775879e-05 3.09944152832e-06 3.91006469727e-05
nmea is running too _slowly_ 0.14456987381
MPU-925x init complete
serial reserve /dev/ttyOP_gps
nmea source for gps source gpsd 1552770457.79
arduino servo found on [u'/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AH06SD0U-if00-port0', 38400]
serialprobe success: /home/pi/.pypilot/servodevice [u'/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AH06SD0U-if00-port0', 38400]
nmea client connected
listening on port 20220 for nmea connections
Traceback (most recent call last):
  File "/usr/local/bin/pypilot", line 11, in <module>
    load_entry_point('pypilot==0.2', 'console_scripts', 'pypilot')()
  File "/usr/local/lib/python2.7/dist-packages/pypilot-0.2-py2.7-linux-armv7l.egg/pypilot/autopilot.py", line 424, in main
    ap.run()
  File "/usr/local/lib/python2.7/dist-packages/pypilot-0.2-py2.7-linux-armv7l.egg/pypilot/autopilot.py", line 232, in run
    self.iteration()
  File "/usr/local/lib/python2.7/dist-packages/pypilot-0.2-py2.7-linux-armv7l.egg/pypilot/autopilot.py", line 397, in iteration
    self.nmea.poll()
  File "/usr/local/lib/python2.7/dist-packages/pypilot-0.2-py2.7-linux-armv7l.egg/pypilot/nmea.py", line 370, in poll
    self.rudder.source.update('servo')
AttributeError: 'Nmea' object has no attribute 'rudder'

**Comment by seandepagnier** [comment]
I have fixed
