### ISSUE TITLE
pypilot_calibration utility doesn't load previously stored values after linux reboot 

### ISSUE THREAD

**Issue by mgrouch** [pypilot/pypilot#160]
heading offset gets reset
wind sensor offset is loaded as 0
locked accelerometer calibration points are not loaded into pypilot_calibration (shows as default)

There are also some errors like this:
`
Unimplemented OBJ format statement 's' on line 's off'
`

Thanks

**Comment by seandepagnier** [comment]
that is a warning, not an error.

What are the values stored in pypilot.conf?

**Comment by seandepagnier** [comment]
It is odd there is no imu.compass.calibration

The settings are not stored to disk immediately.   Perhaps this would be nice for values that don't get updated like amp hours or runtime, but it is to avoid constantly writing the file.    If you change the offset and wait until the change is written to pypilot.conf it should be there on reboot.

The other thing is.. stopping pypilot with systemctl stop should flush changes to pypilot.conf, and this should run at reboot, so I am not quite sure what is going wrong here unless you power cycled.

Anyway, no the wind sensor height is not even proven/tested very well so it is 'hidden' for now.

**Comment by mgrouch** [comment]
ALso locking compass calibration seems has no effect. It still comes back as unlocked.

**Comment by mgrouch** [comment]
Hmm. How a regular user would know to wait?
Usual practice after altering the configuration of a service is to bounce it and see config taking effect.

**Comment by mgrouch** [comment]
I think this can be closed. as long as docs say you need to wait for pypilot to stored config.

**Comment by seandepagnier** [comment]
it should store the config if the service is stopped.
