### ISSUE TITLE
Firware 

### ISSUE THREAD

**Issue by Max194703** [pypilot/pypilot#201]
It is possible to create a firmware update function on the web?

**Comment by seandepagnier** [comment]
Which firmware?    I recently implemented support to update the firmware on the microprocessor on the hat.  It will happen automatically on newer boards.

Or do you mean for pypilot itself on tinypilot?   It could work but only if the pilot is a client with internet access.   Or do you mean, to browse for a file you download and use that?

**Comment by Max194703** [comment]
I mean to be able to upload updates from the web interface, see: https://pcnautic.gitbook.io/autopilot/bediening/webinterface/configuration-configuratie/firmware-upgrade

**Comment by seandepagnier** [comment]
I have not merged this feature into my repository yet but I will consider it for the future.

**Comment by Max194703** [comment]
Ok, tks, buon vento!
