### ISSUE TITLE
Webapp doesn't refresh to show when engaged

### ISSUE THREAD

**Issue by gvaughan67** [pypilot/pypilot#21]
The sliding button on the webapp does not show that it has changed (turn green, etc) when tapped. The page must be refreshed. 

This same problem effects usability of the app in many areas. 

Running Openplotter with latest Pypilot from Github. Browser on iOS, Android, and Openplotter.

**Comment by seandepagnier** [comment]
Did you try on the openplotter
apt install python-gevent-websocket

**Comment by gvaughan67** [comment]
that resolved it, thank you, I'll relay to sailoog.
