### ISSUE TITLE
Last Commit to boatimu.py broke the boat alignment "Boat is level" in calibration. 

### ISSUE THREAD

**Issue by gtborn2fly** [pypilot/pypilot#211]
The last commit to boatimu.py broke the Boat is level button in calibration.  The commit message is "fix changing offsets underway", so there may be more changes in the works.  In that change, the "count down to alignment" block of code (lines 475 to 500) was moved.  This put it in front of the line where the value of "aligned" is set.  "aligned" is used in the code block, so it causes an error.

Moving the lines where "aligned" is set (lines 503 to 505) in from of the "count down to alignment" block of code allows the alignment to complete and the results look correct. (Tested on a raspberry pi 4 with the OpenPlotter 3 Touchscreen image dated 2023-08-04).

**Comment by seandepagnier** [comment]
this was to allow you to change the compass offset while under autopilot control without the course changing...   but it clearly broke alignment.

Thanks for this I will have to rethink
