### ISSUE TITLE
Greek translations

### ISSUE THREAD

**Issue by kagouraki** [pypilot/pypilot#217]
The Greek translations are garbage. Please exclude them. If i find some time i will make them at least readable

**Comment by seandepagnier** [comment]
They are auto-generated and probably pretty shit.

Could you just set the LCD to use english?   

Or do you mean on the web interface?   In the website in the latest image you should be able to set the language.

**Comment by kagouraki** [comment]
I mean in the web interface. In the lcd there is a menu option and you can change the language. I see in the latest firmware you added to choose the language in the web interface. I will try this.

**Comment by seandepagnier** [comment]
If I dont get a greek update for the next version I will take them out.
