### ISSUE TITLE
Web interface buttons move the rudder the wrong way

### ISSUE THREAD

**Issue by chrisclaydon** [pypilot/pypilot#235]
Using the latest release (9th June 2024) and a genuine PyPilot and hydraulic motor controller both made in 2019.
To reproduce:
Open the web interface. Press the > arrow button and the rudder moves to port. Press the < button and it moves to starboard. This is the opposite to what is expected.
Open the OpenCpn plugin, Press the > arrow and the rudder moves correctly to starboard. This demonstrates that the problem must be in the Web UI and not anywhere else, because the plugin interface controls the rudder in the correct direction.

**Comment by seandepagnier** [comment]
I have updated the web control script for version 0.55 it should be fixed.
