### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by sailoog** [pypilot/pypilot#27]
https://github.com/pypilot/pypilot/blob/f0ad106e88d826be0b2a915ed6e4a14d8a3a0155/pypilot/nmea.py#L159

It should be `try:`

**Comment by o-charts** [comment]
Closed by https://github.com/pypilot/pypilot/pull/28

**Comment by sailoog** [comment]
close by https://github.com/pypilot/pypilot/pull/28
