### ISSUE TITLE
Need more details for Arduino

### ISSUE THREAD

**Issue by dmdelorme** [pypilot/pypilot#4]
I would like to build a controller but never used a Arduino. 
I would like more details on type of arduino, type of shunt, ECS and ESC driver. A few close ups would be nice.
I am hopping to bypass the Controller on my Marine pilot 1600.

**Comment by seandepagnier** [comment]
The source code for the controller is in the arduino/motor directory.  From reading the code most questions should be answered.   You could potentially  use various shunts by changing the multiplier.  The basic controller uses a 10 milli ohm shunt.     The ESC I am using is a blue series brushless controller reprogrammed for brushed mode.
