### ISSUE TITLE
Theming of webclient

### ISSUE THREAD

**Issue by FredericGuilbault** [pypilot/pypilot#50]
Hi, between here and the spring I plan to redo the theme of the webclient so it fit Lysmarine look and feel. 

I can do it on my side as a patch of a fork. 
Or I could put a bit more work in it and PR it as dark theme with a GUI theme switcher or CLI argument.

One one hand I prefer contribution then forks, But on the other hand my need is it have to reflect lysmarine look and feel ( mainly based on adapta-nokto work  https://github.com/adapta-project/adapta-gtk-theme ) so it's not much of a common goal. 

So before I start, would you be interested in integrating such PR or you prefer that I keep it on my side  ? As in a what make more sense for pypilot project.

**Comment by seandepagnier** [comment]
I would integrate such a pull request to change the theme.

What do you have in mind?   Could the theme be set via the web
interface?    What would change?  css style or actual layout of the
buttons and control?

Sean

**Comment by FredericGuilbault** [comment]
The usual web way to do this is to add a second CSS file that override the base theme when a specific class placed in the body.   Something like `<body class="dark-theme">` 

Then, there is 2 way to make the magic append.
1) The `dark-theme` class class and it's CSS file could be added on the server side uppon CLI argument or config file. 

2) Or the CSS file is always loaded, And the `dark-theme` class is added by a Javascript event bind to a HTML selector. (This might need a cookie to be persistant across reload. I will have to make some research on this to see if it's possible to avoid the cookie.)
 
In all case Ill try to avoid touching the actual code as possible. So layout should pretty much stay the same. Most of the work will append in a new CSS file.

**Comment by seandepagnier** [comment]
It would be good if the user could change the theme from the web
interface and store the theme in the browser so different
devices/browsers can be set to different themes.   This is probably
closest to #2.

**Comment by FredericGuilbault** [comment]
There is the branch for this feature : https://github.com/FredericGuilbault/pypilot/commits/dark-theme-web

**Comment by FredericGuilbault** [comment]
Preview:
Big:
![big](https://user-images.githubusercontent.com/37122999/74359741-d48f9e00-4d91-11ea-8b79-5690c278c0ad.png)
Small:
![small](https://user-images.githubusercontent.com/37122999/74359751-d8bbbb80-4d91-11ea-8b34-d370c5c3a746.png)
---
Calibration tab
![calibration](https://user-images.githubusercontent.com/37122999/74359760-dce7d900-4d91-11ea-8058-94d089cbd5bc.png)

**Comment by Jamos1988** [comment]
How would one implement this theme?

**Comment by FredericGuilbault** [comment]
@Jamos1988  it's have been merged, so it should be part of pypilot already. 

You need to go on the configuration tab to turn it on.
