### ISSUE TITLE
crc.h: No such file or directory

### ISSUE THREAD

**Issue by Heaventwo** [pypilot/pypilot#56]
When I try the code that is given I get a error message.
The message I get is "crc.h: No such file or directory"
I tried to fix it myself but without any succes.

![Knipsel](https://user-images.githubusercontent.com/63049409/78243738-92a6ec80-74e4-11ea-9236-0119e5409578.PNG)

**Comment by seandepagnier** [comment]
the crc.h is in the same directory as the source
