### ISSUE TITLE
Typo? Engauged should be Engaged

### ISSUE THREAD

**Issue by Fixh1** [pypilot/pypilot#7]
Hi,
You use the word engauged quit a lot in your code (and displayed messages) but shouldn't this be engaged?
I'm not native English but every time I see it it itches a little bit.
:-)

**Comment by seandepagnier** [comment]
It looks like you found a word I didn't know how to spell despite
being a native english speaker!   Thanks!

I will correct the spellings in a few weeks when I get off vacation.
