### ISSUE TITLE
motor.ino enable_pin should be defined as output

### ISSUE THREAD

**Issue by marcobergman** [pypilot/pypilot#72]
Currently, in line 710, it is defined as input. 

This seems to work (!): a logical signal is measurable on the pin and somewhat usable. However, you cannot drive an LED off of it, so it will be an unreliable signal and susceptible to e.g. low rise time.

**Comment by seandepagnier** [comment]
I did not do much with pwm_mode==2 because my vnh2sp30 had such poor
quality control.   If you think it should be output I would accept
this in a pull request because I don't care about mode 2 much, but
again, I am not sure it actually matters.   I'm surprised it is
configured as an input.

Sean

**Comment by marcobergman** [comment]
Fixed in 03-jan-2021 commit; issue closed
