### ISSUE TITLE
unsupported version of the Socket.IO or Engine.IO

### ISSUE THREAD

**Issue by mgrouch** [pypilot/pypilot#83]
Mar 26 14:18:49 lysmarine pypilot_web[32329]: The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)

**Comment by mgrouch** [comment]
Would be nice to show which one it is using 
and which one (supported) it needs and how to install it

**Comment by mgrouch** [comment]
pip3 install "python-socketio<5"

seems fixes it

**Comment by seandepagnier** [comment]
Well this is good to know, but I still don't understand what caused
this, or if pypilot_web can be modified to work with the newer
version.

**Comment by mgrouch** [comment]
what if you grep source files for "unsupported version of the Socket.IO"
including third part modules? Might be there is some kind of version check.

**Comment by marcobergman** [comment]
#79 ;-)

**Comment by mgrouch** [comment]
It seems commits from Apr 25, 2021 broke it again. 
it was working before with <5

**Comment by seandepagnier** [comment]
It works now with the new version of socket library, did you try it?

**Comment by mgrouch** [comment]
Yes I’ve tried with version 5. It doesn’t give error but doesn’t connect from pypilot_web.

**Comment by mgrouch** [comment]
This is how it worked before:

with this install script:

https://github.com/bareboat-necessities/lysmarine_gen/blob/master/install-scripts/4-server/02-pypilot.sh

**Comment by seandepagnier** [comment]
What do you get from

python3
import socketio
socketio.__version__

I have '5.2.1'

**Comment by mgrouch** [comment]
Shows 5.2.1 but pypilot_web can't connect to pypilot.

**Comment by seandepagnier** [comment]
What error do you see?   Does pypilot_client connect?

**Comment by mgrouch** [comment]
pypilot_client connects. 

There are no errors in logs.

**Comment by mgrouch** [comment]
Yes no errors. But pypilot web wouldn’t connect

**Comment by seandepagnier** [comment]
I have updated the dependency script to hopefully get all the correct versions of libraries needed.
