### ISSUE TITLE
keyerror in signalk zeroconf

### ISSUE THREAD

**Issue by marcobergman** [pypilot/pypilot#90]
There is a consistent error at each startup. However, this does not always seem to be a problem.

  File "/usr/local/lib/python3.7/dist-packages/pypilot-0.24-py3.7-linux-armv7l.egg/pypilot/signalk.py", line 124, in add_service
    if properties['swname'] == 'signalk-server':
KeyError: 'swname'

To debug this key error, I edited signalk.py and added a line that outputs the contents of info.properties.items(). It turns out that sometimes this dict is empty. When it is empty, there is no line 'signalk server found 10.10.10.1:3000'. The registration with signalk only proceeds when it is not empty. So here is possibly some non-determinate race condition at play.

See attached file, with three attempts to register with signalk. Only the third attempt succeeds. This happens to be the attempt when info.properties was not empty.

Hope this helps.

[signalk-pypilot.txt](https://github.com/pypilot/pypilot/files/6274946/signalk-pypilot.txt)

**Comment by seandepagnier** [comment]
I recently resolved this.   I found a system with empty dictionary that reproduced it.
