### ISSUE TITLE
pypilot build failure

### ISSUE THREAD

**Issue by mgrouch** [pypilot/pypilot#97]
creating build/temp.linux-aarch64-3.7/pypilot/arduino_servo
aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -c pypilot/arduino_servo/arduino_servo.cpp -o build/temp.linux-aarch64-3.7/pypilot/arduino_servo/arduino_servo.o -Wno-unused-result
pypilot/arduino_servo/arduino_servo.cpp: In member function 'void ArduinoServo::send_params()':
pypilot/arduino_servo/arduino_servo.cpp:372:5: error: duplicate case value
     case 16:
     ^~~~
pypilot/arduino_servo/arduino_servo.cpp:347:21: note: previously used here
     case 0: case 8: case 16:
                     ^~~~
pypilot/arduino_servo/arduino_servo.cpp:373:20: error: 'CLUTCH_PWM_CODE' was not declared in this scope
         send_value(CLUTCH_PWM_CODE, eeprom.local.clutch_pwm);
                    ^~~~~~~~~~~~~~~
error: command 'aarch64-linux-gnu-gcc' failed with exit status 1

**Comment by seandepagnier** [comment]
This should be fixed now
